### ISSUE TITLE
error when you specify root directory containing tmp directory

### ISSUE THREAD

**Issue by khomyakov42** [broccolijs/broccoli-funnel#59]
```
/myproject
   /tmp                // broccoli temporary folder
   Brocfile.js
```

Brocfile.js
```javascript
var Funnel = require('broccoli-funnel');

module.exports = new Funnel(__dirname, {
  include: ['**/*.d.ts'],
  exclude: ['tmp'],
  destDir: 'out'
});
```

```
$cd myproject
$broccoli serve
Serving on http://localhost:4200

Built with error:
Error: ELOOP: too many symbolic links encountered, stat '/home/sergey/Projects/client/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0/tmp/funnel-input_base_path-qEa9xQgy.tmp/0'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at getStat (/home/sergey/Projects/client/node_modules/walk-sync/index.js:108:15)
    at _walkSync (/home/sergey/Projects/client/node_modules/walk-sync/index.js:70:17)
    at _walkSync (/home/sergey/Projects/client/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/home/sergey/Projects/client/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/home/sergey/Projects/client/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/home/sergey/Projects/client/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/home/sergey/Projects/client/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/home/sergey/Projects/client/node_modules/walk-sync/index.js:76:32)

```

**Comment by stefanpenner** [comment]
this is expected, reading from the output of a build will cause a cycle. In the future we should make broccoli proper recognize this and give a more useful error.
