### ISSUE TITLE
Broccoli-funnel - no such file or directory, symlink

### ISSUE THREAD

**Issue by erenalgan** [broccolijs/broccoli-funnel#60]
Very new to Ember & aws world. I'm trying to deploy a simple ember app to ElasticBeanstalk and I'm having the following problem on Win 10 machine. Any help would be appreciated. 

C:\Users\eralgan\Desktop\ElasticBeanstalk\todo>ember deploy production
version: 2.4.2
- build failed
Error: The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, symlink 'C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-ajax\addon' -> 'C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\tmp\funnel-input_base_path-OmJjrelm.tmp\0'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at symlinkWindows (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:90:16)
    at symlinkOrCopySync (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:56:5)
    at C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\node_modules\broccoli-plugin\read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\node_modules\broccoli-plugin\index.js:7:31)
    at new Funnel (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\node_modules\broccoli-funnel\index.js:44:10)
    at Class.Addon.addonJsFiles (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\lib\models\addon.js:692:30)
    at Class.Addon.processedAddonJsFiles (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\lib\models\addon.js:722:33)
    at Class.Addon.compileAddon (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\lib\models\addon.js:632:22)
    at Class.Addon.treeForAddon (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\lib\models\addon.js:403:24)
    at Class._treeFor (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\lib\models\addon.js:322:31)
    at Class.treeFor (C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\lib\models\addon.js:290:19)
    at C:\Users\eralgan\Desktop\ElasticBeanstalk\todo\node_modules\ember-cli\lib\broccoli\ember-app.js:446:20
    at Array.map (native)

Pipeline aborted

**Comment by erenalgan** [comment]
Just in case: 
C:\Users\eralgan\Desktop\ElasticBeanstalk\todo>npm ls broccoli-funnel broccoli-merge-trees broccoli-caching-writer ember-cli-moment
todo@0.0.0 C:\Users\eralgan\Desktop\ElasticBeanstalk\todo
├─┬ ember-cli@2.4.2
│ ├─┬ broccoli-concat@2.2.0
│ │ └── broccoli-caching-writer@2.2.1
│ ├─┬ broccoli-config-loader@1.0.0
│ │ └── broccoli-caching-writer@2.2.1
│ ├── broccoli-funnel@1.0.1
│ └── broccoli-merge-trees@1.1.1
├─┬ ember-cli-babel@5.1.6
│ ├─┬ broccoli-babel-transpiler@5.5.0
│ │ └── broccoli-merge-trees@1.1.1
│ └── broccoli-funnel@1.0.1
├─┬ ember-cli-qunit@1.3.0
│ ├─┬ broccoli-babel-transpiler@5.5.0
│ │ └── broccoli-funnel@1.0.1
│ ├─┬ broccoli-concat@2.2.0
│ │ └── broccoli-caching-writer@2.2.1
│ └── broccoli-merge-trees@1.1.1
├─┬ ember-cli-sri@2.1.0
│ └─┬ broccoli-sri-hash@2.1.0
│   └── broccoli-caching-writer@2.2.1
└─┬ ember-data@2.4.1
  ├─┬ broccoli-babel-transpiler@5.5.0
  │ └── broccoli-funnel@1.0.1
  └── broccoli-merge-trees@1.1.1

**Comment by lllama** [comment]
I'm having the same issue. Not sure whether this is related to #53

**Comment by orgilnm11** [comment]
same issue with me , anyone fixed?

**Comment by JerryLagos** [comment]
Just you need install http://broccolijs.com/   npm install -g broccoli-cli and

**Comment by stefanpenner** [comment]
Many things have been fixed, if there is still and issue please provide a repo that demonstrates this and I will gladly debug + reopen

**Comment by wpirtle** [comment]
I am getting this error and I do not see a solution that works.  Why is this item closed?

λ ng serve
(node:2844) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
The Broccoli Plugin: [Funnel] failed with:
Error: EISDIR: illegal operation on a directory, symlink 'Z:\udemy\Angular2\recipe2\src' -> 'Z:\udemy\Angular2\recipe2\tmp\funnel-input_base_path-rOujc2w6.tmp\0'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at symlinkWindows (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\symlink-or-copy\index.js:101:16)
    at symlinkOrCopySync (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\symlink-or-copy\index.js:53:5)
    at Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\broccoli-plugin\read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at new Funnel (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\broccoli-funnel\index.js:44:10)
    at Angular2App._buildInputTree (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\lib\broccoli\angular2-app.js:92:7)
    at new Angular2App (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\lib\broccoli\angular2-app.js:51:41)
    at module.exports (Z:\udemy\Angular2\recipe2\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (Z:\udemy\Angular2\recipe2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by stefanpenner** [comment]
@wpirtle the [comment before yours](https://github.com/broccolijs/broccoli-funnel/issues/60#issuecomment-220854357) explains why it is closed, and what steps (buy a issue submitter) are required to reopen it.

**Comment by wpirtle** [comment]
I suppose that fixing many things, just not the thing that is causing the error is reason for closing the issue.  If only real programming was that easy.

**Comment by stefanpenner** [comment]
@wpirtle lets be charitable here, and assume the fixes addressed problems that would have also caused the above symptom (which is in-fact the case).

> just not the thing that is causing the error is reason for closing the issue

Unfortunately without a reproduction (provided by the issuer) the root cause of this issue may have gone unidentified.

As requested above, please provided a reproduction, which will help us identify and address the root cause of your error.

**Comment by cobbspur** [comment]
I am getting this with current Ghost master: https://github.com/TryGhost/Ghost/commit/71282a241e76608df5d99112df005ebbc7a3204b

I am running on Node version 4.4.7
npm version 2.15.8

Error message: 
``` 
Running "shell:ember:dev" (shell) task
...
Build failed.
The Broccoli Plugin: [Funnel: Funnel: index.html] failed with:
Error: ENOENT: no such file or directory, lstat '/Users/cobbspur/GHOST/Ghost/core/client/tmp/funnel-input_base_path-FNm1HTuv.tmp/0/index.html'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at symlink (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:60:26)
    at Function.symlinkOrCopySync [as sync] (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:55:5)
    at Funnel._copy (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:393:19)
    at Funnel.processFile (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:376:8)
    at Funnel.applyPatch [as _applyPatch] (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:293:12)
    at Funnel.<anonymous> (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:248:10)
    at Array.forEach (native)
    at Funnel.processFilters (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:247:9)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:44:10)
    at EmberApp.index (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/lib/broccoli/ember-app.js:614:15)
    at EmberApp.toArray (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/lib/broccoli/ember-app.js:1565:10)
    at EmberApp.toTree (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
    at module.exports (/Users/cobbspur/GHOST/Ghost/core/client/ember-cli-build.js:144:16)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/lib/models/builder.js:54:19)
    at CoreObject.module.exports.Task.extend.init (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/lib/models/builder.js:89:10)
    at CoreObject.superWrapper [as init] (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/Users/cobbspur/GHOST/Ghost/core/client/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)

```

Please let me know if there is any other information I need to provide.

**Comment by stefanpenner** [comment]
@cobbspur  awesome, let me take a look.

**Comment by stefanpenner** [comment]
@cobbspur hmm, unable to reproduce but that doesn't mean something isn't up.

@ErisDS  is this also affecting your usage of ghost?

**Comment by cobbspur** [comment]
@stefanpenner thanks for looking into this and sorry for wasting your time.

It appears the Ghost-Admin submodule was in a strange state. Resetting the submodule to the head branch fixed this problem for me. :)

**Comment by stefanpenner** [comment]
@cobbspur no problem, better safe then sorry.

**Comment by tillerstarredwards** [comment]
I'm running into this issue on my windows box.  We recently installed ember-cli-d3 into a project and while it works on the macs, it dies on windows with the following error:

```
 The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, open 'E:\Work\BitBucket\New folder\tmp\funnel-output_path-W6hyqoN3.tmp\d3-plugins-dist\adnan-wahab\pathgl\named-amd\main.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at symlinkWindows (E:\Work\BitBucket\New folder\node_modules\symlink-or-copy\index.js:106:18)
    at Function.symlinkOrCopySync [as sync] (E:\Work\BitBucket\New folder\node_modules\symlink-or-copy\index.js:53:5)
    at Funnel._copy (E:\Work\BitBucket\New folder\node_modules\broccoli-funnel\index.js:393:19)
    at Funnel.processFile (E:\Work\BitBucket\New folder\node_modules\broccoli-funnel\index.js:376:8)
    at Funnel.applyPatch [as _applyPatch] (E:\Work\BitBucket\New folder\node_modules\broccoli-funnel\index.js:293:12)
    at Funnel.<anonymous> (E:\Work\BitBucket\New folder\node_modules\broccoli-funnel\index.js:248:10)
    at Array.forEach (native)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (E:\Work\BitBucket\New folder\node_modules\broccoli-plugin\index.js:7:31)
    at new Funnel (E:\Work\BitBucket\New folder\node_modules\broccoli-funnel\index.js:44:10)
    at Funnel (E:\Work\BitBucket\New folder\node_modules\broccoli-funnel\index.js:42:43)
    at CoreObject.module.exports.treeForVendor (E:\Work\BitBucket\New folder\node_modules\ember-cli-d3\index.js:36:43)
    at CoreObject._treeFor (E:\Work\BitBucket\New folder\node_modules\ember-cli\lib\models\addon.js:358:33)
    at CoreObject.treeFor (E:\Work\BitBucket\New folder\node_modules\ember-cli\lib\models\addon.js:326:21)
    at E:\Work\BitBucket\New folder\node_modules\ember-cli\lib\broccoli\ember-app.js:465:20
    at Array.map (native)
    at EmberApp.addonTreesFor (E:\Work\BitBucket\New folder\node_modules\ember-cli\lib\broccoli\ember-app.js:463:30)
    at EmberApp._processedVendorTree (E:\Work\BitBucket\New folder\node_modules\ember-cli\lib\broccoli\ember-app.js:919:29) 

```

I'm able to reproduce with a completely new project by using ember init, and then updating package.json to include` "ember-cli-d3": "1.1.7",`doing the npm and bower installs and then finally calling ember serve.

**Comment by wpirtle** [comment]
I found a solution to my problem which was I was running on a drive formatted as FAT where the symlinks will not work.  I changed to an NTFS formatted drive and everything works.

**Comment by tillerstarredwards** [comment]
My drive is NTFS...

**Comment by hjdivad** [comment]
> I'm able to reproduce with a completely new project by using ember init, and then updating package.json to include"ember-cli-d3": "1.1.7",doing the npm and bower installs and then finally calling ember serve.

@tillerstarredwards what is your `ember --version`?

**Comment by tillerstarredwards** [comment]
ember-cli: 2.6.2
node: 6.3.0
os: win32 x64

**Comment by stefanpenner** [comment]
@wpirtle good to know

@tillerstarredwards mind sharing the exact app that has this issue (I want to be sure to not be chasing ghosts trying to recreate the issue).

The the issue seems to be very different then the original posting (which seems to be resolved). I'm going to open a fresh issue.

**Comment by stefanpenner** [comment]
@wpirtle your issue still seems to be different then that of both @tillerstarredwards and @erenalgan (the error message appears different).

**Comment by tillerstarredwards** [comment]
Stephan.... you want the folder?
All my drives are NTFS...

**Comment by stefanpenner** [comment]
@tillerstarredwards would love it, although I am unsure about NTFS actually being the issue here. All my windows tests, and our windows CI runs using NTFS....

**Comment by iamrauu** [comment]
I'm also cursed with a similar issue....

**File system**: NTFS

ember-cli: 2.8.0
node: 6.5.0
os: win32 x64
--

The Broccoli Plugin: [Funnel: Funnel: index.html] failed with:                
Error: UNKNOWN: unknown error, symlink 'X:\testapp\ember\app' -> 'X
:\testapp\ember\tmp\funnel-input_base_path-ZoWtiw5C.tmp\0'         
    at Error (native)                                                         
    at Object.fs.symlinkSync (fs.js:1054:18)                                  
    at symlinkWindows (X:\testapp\ember\node_modules\symlink-or-cop
y\index.js:101:16)                                                            
    at symlinkOrCopySync (X:\testapp\ember\node_modules\symlink-or-
copy\index.js:53:5)                                                           
    at X:\testapp\ember\node_modules\broccoli-plugin\read_compat.js
:58:9                                                                         
    at tryCatch (X:\testapp\ember\node_modules\rsvp\dist\rsvp.js:53
8:12)                                                                         
    at invokeCallback (X:\testapp\ember\node_modules\rsvp\dist\rsvp
.js:553:13)                                                                   
    at publish (X:\testapp\ember\node_modules\rsvp\dist\rsvp.js:521
:7)                                                                           
    at flush (X:\testapp\ember\node_modules\rsvp\dist\rsvp.js:2373:
5)                                                                            
    at _combinedTickCallback (internal/process/next_tick.js:67:7)             
                                                                              
The broccoli plugin was instantiated at:                                      
    at Funnel.Plugin (X:\testapp\ember\node_modules\broccoli-plugin
\index.js:7:31)                                                               
    at new Funnel (X:\testapp\ember\node_modules\broccoli-funnel\in
dex.js:57:10)                                                                 
    at EmberApp.index (X:\testapp\ember\node_modules\ember-cli\lib\
broccoli\ember-app.js:641:15)                                                 
    at EmberApp.toArray (X:\testapp\ember\node_modules\ember-cli\li
b\broccoli\ember-app.js:1605:10)                                              
    at EmberApp.toTree (X:\testapp\ember\node_modules\ember-cli\lib
\broccoli\ember-app.js:1628:30)                                               
    at module.exports (X:\testapp\ember\ember-cli-build.js:62:14)  
    at CoreObject.setupBroccoliBuilder (X:\testapp\ember\node_modul
es\ember-cli\lib\models\builder.js:74:19)                                     
    at CoreObject.init (X:\testapp\ember\node_modules\ember-cli\lib
\models\builder.js:54:10)                                                     
    at CoreObject.superWrapper [as init] (X:\testapp\ember\node_mod
ules\core-object\lib\assign-properties.js:32:18)                              
    at CoreObject.Class (X:\testapp\ember\node_modules\core-object\
core-object.js:32:33)                                                         

----

**Comment by kenperregaux** [comment]
Is there any resolution to this I am running into the same problem as 'tillerstarredwards' using both ember-d3 and ember-d3-cli.

Node: v6.9.2
Ember: 2.10.0
os: win32 x64

**Comment by MonkeyKiki** [comment]
@wpirtle I had the same error, I used the same solution, thank you

**Comment by mateuszrusiecki** [comment]
I had similar error after npm install:
The Broccoli Plugin: [ConfigLoader] failed with:
Error: ENOENT: no such file or directory, symlink(...)

In my case, the only thing that help, was to restart ember server

ember-cli: 2.6.2
node: 6.11.2
os: darwin x64

**Comment by hefox** [comment]
I got this error because I was somehow missing index.html (not sure how that happened)
